apiVersion: v1
kind: Service
metadata:
  name: deconz-service
  labels:
    appName: deconz
spec:
  type: LoadBalancer
  selector:
    app: deconz
  ports:
    - protocol: TCP
      name: "web"
      port: 80
      targetPort: 80
    - protocol: TCP
      name: "ws"
      port: 443
      targetPort: 443
    - protocol: TCP
      name: "vnc"
      port: 6080
      targetPort: 6080
